### PR TITLE
docs: add macos instructions

### PR DESCRIPTION
**Pull request by evilrobot-01**
Simple instructions for configuring and running on macOS on Apple silicon. Draft just to share the instructions until they are validated and more information can be added.

Reliant on https://github.com/stiiifff/trappist-extra/pull/3

### CODE REVIEW

**Comment by stiiifff** [comment]
Looks great, thanks !

**Comment by Daanvdplas** [comment]
After "sdkmanager ..." I got the error:
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

This fixed it ([ref](https://stackoverflow.com/questions/44009058/even-though-jre-8-is-installed-on-my-mac-no-java-runtime-present-requesting-t)):
sudo ln -sfn /opt/homebrew/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk

**Comment by evilrobot-01** [comment]
Yeah, the '# install required packages, following additional instructions in resulting caveats for each package' bit should've indicated to follow the additional brew instructions for each package, but maybe they got lost when batch installing...

**Comment by evilrobot-01** [comment]
Replaced by #11

**Pull request closed without merging**
